### ISSUE TITLE
Compilation tracks not included in Artist view

### ISSUE THREAD

**Issue by certuna** [deluan/navidrome#94]
![image](https://user-images.githubusercontent.com/62144283/76629075-0be29d80-653e-11ea-8dd7-ac9472258802.png)

This album is a V/A compilation. When I filter on the artist though:
`http://localhost:4533/app#/album?filter={%22artist_id%22:%22cd4187b19abbcad3526c0e87460c19c8%22}&order=ASC&sort=year`
I see only the regular albums of the artist:

![image](https://user-images.githubusercontent.com/62144283/76629788-2701dd00-653f-11ea-802b-1d8a7dde5b12.png)

The compilation tracks are not included, indicating that the filter only works on Album Artists, not Artists. Should probably be fixable with a WHERE EXISTS in the underlying sql query, so both Album Artist and Artist fields are included (and possibly in the future, fields like Composer, Arranger, Producer, etc too)

**Comment by deluan** [comment]
Hey @certuna, I see you filtered the albums by clicking in the artist in the artist view, right? When you do this, the UI goes to the album view, setting the filter based on the artist ID. This navigation, though simple to implement, has a few drawbacks, one is what you see here.

I just pushed a new filter implementation (in the "Search" field) that allow you to filter by any relevant field in a given view. Ex, in the album view, it filters by album name, artist and album artist.

Can you please try it? Let me know if this new filter can handle your use case.

If you use Docker, it is available in the latest develop image: `deluan/navidrome:develop`

**Comment by deluan** [comment]
Hey @certuna, I fixed this issue and also added a new Artist filter to the album view, making the selected artist more explicitly and allowing more flexibility to the navigation.

A new image will be available soon (`deluan/navidrome:develop`)

Please let me know if this fixes the issue for you. If you still have any problems, feel free to reopen this issue.

**Comment by certuna** [comment]
No it's not fixed unfortunately.

Case: a compilation album with multiple tracks by different artists
Go to Artist, search, and put in the artist of one of these tracks -> no results

Basically, navidrome does not search/filter across both the album artist and track artist field.
Ideally you'd set search up like iTunes and most other music libraries, ie a phrase searches over all fields in a single search box, not different boxes for artist/album/songs.

Also there's a new bug where if you add an album, artist and track filter, and try to remove them, you get a "something went wrong" error.

**Comment by deluan** [comment]
I'll take another look at the search, but I'm pretty sure the filter (both clicking in the artist from the artist view, and using the new artist filter from the album view) are working. Can you confirm the version you tested, please?

Re: "Something Went Wrong" error, I've seen it a couple of times, not sure what is causing it, may be a bug in the underlying frameworks. Will investigate a bit more. A workaround is to refresh the page, but this causes the player to stop... :(

**Comment by deluan** [comment]
Yeah, it is not searching against all artists of a compilation, but filter should be working properly. I may reimplement search indexing to handle this, and cater for #121

**Comment by deluan** [comment]
Hey @certuna, I'm now adding all artists from the album in the album searchable field. This should solve this issue. I'll be releasing a new version including this change tomorrow.

Let me know if this fixes the issue for you.

**Comment by certuna** [comment]
I don't think you can close it just yet: with Track Artists that are only featured on compilations:
- searching the artist in the Album view: works
- searching the artist in the Songs view: works
- searching the artist in the Artist view: does not work - which is unfortunate since most users will probably search for an artist in the Artist view

**Comment by deluan** [comment]
This is because I don't add artists that only appears in compilations in the artist list. That is by design, as I (personally) have a lot of compilations and don't care about all artists in those. What we could do is add a configuration option that changes this behaviour.

If you feel this is a nice feature to have, I think this should be a separated issue. What do you think?

**Comment by certuna** [comment]
Personally:

I would fold all "person or group" fields that navidrome has in its DB now into one searchable list: the fields it currently supports (album artist, track artist) and any future fields it's going to support later (composer, remixer, producer, arranger, lyricist, etc).

Then if I want to expose an album artists-only list, I'd make some sub-trees under Artist on the left (Album Artists, Composers, etc), which would respectively filter out artists with only compilation appearances, no composer credits, etc. In terms of SQL queries that shouldn't be too difficult.

I'd also subdivide the artist page (currently `http://localhost:4533/app/#/album?filter={%22artist_id%22:%22xxx%22}` ) in sections by role, so an artist page would be a list of: albums - compilation appearances - composer - producer - remixer - arranger - lyricist - etc.

**Comment by deluan** [comment]
That makes sense. I see 2 new feature requests:

1. Add all artist-related fields to the `artists` table and enable filter artists by "only compilation appearances, no composer credits, etc" in the artists list view

2. Subdivide the artist page in sections. (this will probably be implemented when we have a proper artist view, and not just a filtered album list view)

No rush, but can you please create issues with those, linking to your comment above? 

Thanks a lot for your contributions!
